-- Seed the complete Tesla Fleet Telemetry catalog.
--
-- GENERATED FILE - do not edit by hand.
-- Regenerate with: python3 scripts/build-catalog.py \
--                    --proto <vehicle_data.proto> \
--                    --csv  "<path>/fleet_streaming_fields.csv"
--
-- FRS-010 F03-R07: every field is catalogued so widening the collected
-- subset is a config change, not a schema migration.
--
-- field rows    272
-- collected     14
-- source sha256 5cd3a9c526f0cddda75cfac3c37e82e51e333f8dd49b0c6beeffab212bf43edf
--
-- Idempotent: this file deletes and re-inserts the two catalogs, so
-- re-running it produces an identical row set (F03-R08). The load is
-- recorded in tesla_catalog_load for staleness auditing (F03-R09).

DELETE FROM tesla_field_enum_value;
DELETE FROM tesla_field_enum_def;
DELETE FROM tesla_field_catalog;

INSERT INTO tesla_field_catalog (
  field_key, field_number, category, value_type, vehicle_data_equivalent,
  description, proto_enum_name, collection_tier, collected, collection_group,
  min_delta, sensitivity, is_broken, min_firmware_version,
  is_deprecated, is_experimental, is_semitruck, source
) VALUES
  ('Unknown', 0, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto'),
  ('DriveRail', 1, 'Driving', 'boolean', NULL, 'On/Off drive power state. All ECUs related to drive are ready/powered. Typically means brake pedal is pressed + key authenticated or driving.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeState', 2, 'Charging', 'string', NULL, 'The non-detailed charge state of the vehicle. See DetailedChargeState for detailed charge state data.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BmsFullchargecomplete', 3, 'Charging', 'boolean', NULL, 'Indicates BMS is fully charged.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('VehicleSpeed', 4, 'Driving', 'real', 'drive_state.speed', 'The speed of the vehicle is miles per hour.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Odometer', 5, 'Vehicle State', 'real', 'vehicle_state.odometer', 'The number of miles the vehicle has driven. Beginning with firmware version 2025.2.6, the minimum delta for Odometer is set to 0.1 by default.', NULL, 'event', 1, 'vehicleState', 0.1, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('PackVoltage', 6, 'Charging', 'real', NULL, 'Voltage measured on the battery side of the HV contactors.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('PackCurrent', 7, 'Charging', 'real', NULL, 'Current measured at the HV contactors of the HV battery.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Soc', 8, 'Charging', 'real', 'charge_state.usable_battery_level', 'The usable state of charge of the vehicle, as a percent of total battery capacity.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DCDCEnable', 9, 'Charging', 'boolean', NULL, 'The state of the PCS''s DCDC enable line.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Gear', 10, 'Driving', 'enum', 'drive_state.shift_state', 'Detects the current operating gear reported by the drive inverter.', 'ShiftState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('IsolationResistance', 11, 'Service', 'real', NULL, 'Resistance between HV bus and chassis.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('PedalPosition', 12, 'Driving', 'real', NULL, 'The position of the accelerator pedal.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BrakePedal', 13, 'Driving', 'boolean', NULL, 'Status of the brake pedal.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiStateR', 14, 'Powertrain', 'enum', NULL, 'Rear drive inverter state.', 'DriveInverterState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiHeatsinkTR', 15, 'Powertrain', 'real', NULL, 'Rear drive inverter heatsink temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiAxleSpeedR', 16, 'Powertrain', 'real', NULL, 'Rear drive inverter motor speed normalized at axle level.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiTorquemotor', 17, 'Powertrain', 'real', NULL, 'Torque commanded to the drive unit, referred to the axle/wheel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiStatorTempR', 18, 'Powertrain', 'real', NULL, 'Rear Drive Unit stator temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiVBatR', 19, 'Powertrain', 'real', NULL, 'Rear drive inverter measured battery voltage.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DiMotorCurrentR', 20, 'Powertrain', 'real', NULL, 'Rear drive inverter motor current.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Location', 21, 'Location', 'Location', 'drive_state.latitude, drive_state.longitude', 'The latitude and longitude of the vehicle. Beginning with firmware version 2025.2.6, specifying minimum delta for location values is possible. Changes in distance are measured in meters.', NULL, 'never', 0, NULL, NULL, 'location', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('GpsState', 22, 'Location', 'boolean', NULL, 'If GPS lock is acquired.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('GpsHeading', 23, 'Location', 'real', 'drive_state.heading', 'The orientation of the vehicle. 0 represents North, 90 represents East, etc.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('NumBrickVoltageMax', 24, 'Charging', 'integer', NULL, 'Brick number with maximum voltage (1 indexed).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BrickVoltageMax', 25, 'Charging', 'real', NULL, 'Brick voltage maximum.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('NumBrickVoltageMin', 26, 'Charging', 'integer', NULL, 'Brick number with minimum voltage (1 indexed).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BrickVoltageMin', 27, 'Charging', 'real', NULL, 'Brick voltage minimum.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('NumModuleTempMax', 28, 'Charging', 'integer', NULL, 'The max thermistor temperature module ID.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ModuleTempMax', 29, 'Charging', 'real', NULL, 'The maximum thermistor temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('NumModuleTempMin', 30, 'Charging', 'integer', NULL, 'The min thermistor temperature module ID.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ModuleTempMin', 31, 'Charging', 'real', NULL, 'The minimum thermistor temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('RatedRange', 32, 'Charging', 'real', 'charge_state.battery_range', 'The officially rated range of the vehicle given its current state of charge.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Hvil', 33, 'Powertrain', 'enum', NULL, 'The state of the high voltage interlock.', 'HvilStatus', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DCChargingEnergyIn', 34, 'Charging', 'real', 'charge_state.charge_energy_added', 'The amount of energy in kWh added during a charging session. This is measured at the battery. It can be relied upon for both AC and DC charging.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DCChargingPower', 35, 'Charging', 'real', 'charge_state.charger_power', 'The kilowatts added during a DC charging session.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ACChargingEnergyIn', 36, 'Charging', 'real', NULL, 'The amount of energy in kWh added during an AC charging session. This is measured from the charger. This field should be ignored during DC charging.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ACChargingPower', 37, 'Charging', 'real', 'charge_state.charger_power', 'Total AC charger input power.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeLimitSoc', 38, 'Charging', 'integer', 'charge_state.charge_limit_soc', 'The state of charge at which charging will terminate, as a percentage of battery capacity.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('FastChargerPresent', 39, 'Charging', 'boolean', 'charge_state.fast_charger_present', 'Is a fast charger is present.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('EstBatteryRange', 40, 'Charging', 'real', 'charge_state.est_battery_range', 'The estimated range of the vehicle given its current state of charge. Takes driving conditions into account.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('IdealBatteryRange', 41, 'Charging', 'real', NULL, 'The current range of the vehicle, assuming ideal conditions (speed, weather, etc).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BatteryLevel', 42, 'Charging', 'real', 'charge_state.battery_level', 'The state of charge of the vehicle, as a percent of total battery capacity.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TimeToFullCharge', 43, 'Charging', 'real', 'charge_state.minutes_to_full_charge, charge_state.time_to_full_charge', 'The number of hours until charging is complete. If the charge session is part of a trip, this is the time until ready to continue. Otherwise, this is time until the user set limit (specified by ChargeLimitSoc).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ScheduledChargingStartTime', 44, 'Charging', 'timestamp', 'charge_state.scheduled_charging_start_time', 'The time charging is scheduled to begin. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ScheduledChargingPending', 45, 'Charging', 'boolean', 'charge_state.scheduled_charging_pending', 'If a charge session is scheduled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ScheduledDepartureTime', 46, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto'),
  ('PreconditioningEnabled', 47, 'Charging', 'boolean', 'charge_state.preconditioning_enabled', 'If the vehicle is preconditioning.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ScheduledChargingMode', 48, 'Charging', 'enum', 'charge_state.scheduled_charging_mode', 'The mode for scheduled charging.', 'ScheduledChargingModeValue', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeAmps', 49, 'Charging', 'real', 'charge_state.charger_actual_current', 'AC charger''s sensed input line current.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeEnableRequest', 50, 'Charging', 'boolean', 'charge_state.charge_enable_request', 'If charging is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargerPhases', 51, 'Charging', 'integer', 'charge_state.charger_phases', 'The number of phases available from the connected charger.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargePortColdWeatherMode', 52, 'Charging', 'boolean', 'charge_state.charge_port_cold_weather_mode', 'Indicates whether the charge port is in cold weather mode.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeCurrentRequest', 53, 'Charging', 'integer', 'charge_state.charge_current_request', 'The requested amps to charge the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('ChargeCurrentRequestMax', 54, 'Charging', 'integer', 'charge_state.charge_current_request_max', 'The maximum available amps available to charge.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('BatteryHeaterOn', 55, 'Charging', 'boolean', 'climate_state.battery_heater_on', 'If the battery is actively heating itself. This may be done in cold weather or when preconditioning for supercharging. This field is not available on Pre-2021 Model S/X.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('NotEnoughPowerToHeat', 56, 'Charging', 'boolean', 'charge_state.not_enough_power_to_heat', 'If the battery does not have enough power available to heat itself.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SuperchargerSessionTripPlanner', 57, 'Charging', 'boolean', 'charge_state.supercharger_session_trip_planner', 'If the current supercharging session is part of a trip plan.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DoorState', 58, 'Vehicle State', 'enum', 'vehicle_state.df, vehicle_state.dr, vehicle_state.pf, vehicle_state.pr, vehicle_state.ft, vehicle_state.rt', 'The doors which are currently open. This field has passenger front and driver rear doors swapped in firmware versions prior to 2024.44.32.', 'Doors', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Locked', 59, 'Safety', 'boolean', 'vehicle_state.locked', 'If the vehicle is locked.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('FdWindow', 60, 'Vehicle State', 'enum', 'vehicle_state.fd_window', 'The state of the front driver window.', 'WindowState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('FpWindow', 61, 'Vehicle State', 'enum', 'vehicle_state.fp_window', 'The state of the front passenger window.', 'WindowState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('RdWindow', 62, 'Vehicle State', 'enum', 'vehicle_state.rd_window', 'The state of the rear driver window.', 'WindowState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('RpWindow', 63, 'Vehicle State', 'enum', 'vehicle_state.rp_window', 'The state of the rear passenger window.', 'WindowState', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('VehicleName', 64, 'Vehicle Configuration', 'string', 'vehicle_state.vehicle_name', 'The nickname of the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SentryMode', 65, 'Vehicle State', 'enum', 'vehicle_state.sentry_mode', 'The current state of sentry mode.', 'SentryModeState', 'on_change', 1, '$vehicleState', NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SpeedLimitMode', 66, 'Vehicle State', 'boolean', 'vehicle_state.speed_limit_mode.active', 'If speed limit mode is enabled.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('CurrentLimitMph', 67, 'Vehicle State', 'real', 'vehicle_state.speed_limit_mode.current_limit_mph', 'The maximum speed the vehicle is allowed to travel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Version', 68, 'Vehicle Configuration', 'string', 'vehicle_state.car_version', 'The current firmware version of the vehicle. In firmware versions earlier than 2024.44, this field returned the version of an available software update. This data is available through SoftwareUpdateVersion.', NULL, 'once', 1, '$vehicleInfo', NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsPressureFl', 69, 'Service', 'real', 'vehicle_state.tpms_pressure_fl', 'The last measured tire pressure of the front left tire in bar.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsPressureFr', 70, 'Service', 'real', 'vehicle_state.tpms_pressure_fr', 'The last measured tire pressure of the front right tire in bar.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsPressureRl', 71, 'Service', 'real', 'vehicle_state.tpms_pressure_rl', 'The last measured tire pressure of the rear left tire in bar. Not relevant for Semi-trucks.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsPressureRr', 72, 'Service', 'real', 'vehicle_state.tpms_pressure_fr', 'The last measured tire pressure of the rear right tire in bar. Not relevant for Semi-trucks.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SemitruckTpmsPressureRe1L0', 73, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s middle axle left tire(s) in bar. L0 and L1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe1L1', 74, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s middle axle left tire(s) in bar. L0 and L1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe1R0', 75, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s middle axle right tire(s) in bar. R0 and R1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe1R1', 76, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s middle axle right tire(s) in bar. R0 and R1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe2L0', 77, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s rear axle left tire(s) in bar. L0 and L1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe2L1', 78, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s rear axle left tire(s) in bar. L0 and L1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe2R0', 79, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s rear axle right tire(s) in bar. R0 and R1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTpmsPressureRe2R1', 80, 'Service', 'real', NULL, 'The last measured tire pressure of the Semi''s rear axle right tire(s) in bar. R0 and R1 report measurements from one tire each from the dually.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('TpmsLastSeenPressureTimeFl', 81, 'Service', 'timestamp', 'vehicle_state.tpms_last_seen_pressure_time_fl', 'The time the front left tire''s pressure was last measured. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsLastSeenPressureTimeFr', 82, 'Service', 'timestamp', 'vehicle_state.tpms_last_seen_pressure_time_fr', 'The time the front right tire''s pressure was last measured. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsLastSeenPressureTimeRl', 83, 'Service', 'timestamp', 'vehicle_state.tpms_last_seen_pressure_time_rl', 'The time the rear left tire''s pressure was last measured. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('TpmsLastSeenPressureTimeRr', 84, 'Service', 'timestamp', 'vehicle_state.tpms_last_seen_pressure_time_rr', 'The time the rear right tire''s pressure was last measured. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('InsideTemp', 85, 'Climate', 'real', 'climate_state.inside_temp', 'Estimated temperature of the cabin (in Celsius). This field frequently changes in small increments and setting a minimum delta is recommended. This field frequently changes in small increments and setting a minimum delta is recommended.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('OutsideTemp', 86, 'Climate', 'real', 'climate_state.outside_temp', 'Filtered ambient temperature based on vehicle speed.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SeatHeaterLeft', 87, 'Climate', 'integer', 'climate_state.seat_heater_left', 'The level of the front left seat heater. Values range from 0 (off) to 3 (high).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SeatHeaterRight', 88, 'Climate', 'integer', 'climate_state.seat_heater_right', 'The level of the right seat heater. Values range from 0 (off) to 3 (high).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SeatHeaterRearLeft', 89, 'Climate', 'integer', 'climate_state.seat_heater_rear_left', 'The level of the rear left seat heater. Values range from 0 (off) to 3 (high).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SeatHeaterRearRight', 90, 'Climate', 'integer', 'climate_state.seat_heater_rear_right', 'The level of the rear right seat heater. Values range from 0 (off) to 3 (high).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SeatHeaterRearCenter', 91, 'Climate', 'integer', 'climate_state.seat_heater_rear_center', 'The level of the rear center seat heater. Values range from 0 (off) to 3 (high).', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('AutoSeatClimateLeft', 92, 'Climate', 'boolean', 'climate_state.auto_seat_climate_left', 'If the left front seat has auto seat climate enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('AutoSeatClimateRight', 93, 'Climate', 'boolean', 'climate_state.auto_seat_climate_right', 'If the right front seat has auto seat climate enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DriverSeatBelt', 94, 'Safety', 'boolean', NULL, 'Indication that the driver has unbuckled their seat belt.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('PassengerSeatBelt', 95, 'Safety', 'enum', NULL, 'This field improperly reports if the 2nd row center seat belt is buckled.', 'BuckleStatus', 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('DriverSeatOccupied', 96, 'Vehicle State', 'boolean', NULL, 'Driver presence, determined by combination of sources depending on platform.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('SemitruckPassengerSeatFoldPosition', 97, 'Vehicle State', 'enum', NULL, 'Status of the Semi passenger seat position.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('LateralAcceleration', 98, 'Driving', 'real', NULL, 'The lateral acceleration of the vehicle measured in m/s^2.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('LongitudinalAcceleration', 99, 'Driving', 'real', NULL, 'The longitudinal acceleration of the vehicle measured in m/s^2.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('Deprecated_2', 100, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 1, 0, 0, 'proto'),
  ('CruiseSetSpeed', 101, 'Driving', 'real', NULL, 'Cruise control set point.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('LifetimeEnergyUsed', 102, 'Charging', 'real', NULL, 'Total energy-lost kWh count during discharging.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('LifetimeEnergyUsedDrive', 103, 'Driving', 'real', NULL, 'Energy (in kWh) discharged from the battery packs while the vehicle is in a drive power state. Semi-truck only.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTractorParkBrakeStatus', 104, 'Vehicle State', 'enum', NULL, 'The state of the Semi''s tractor park brake.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('SemitruckTrailerParkBrakeStatus', 105, 'Vehicle State', 'enum', NULL, 'The state of the Semi''s trailer park brake.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 1, 'proto+csv'),
  ('BrakePedalPos', 106, 'Driving', 'real', NULL, 'Master cylinder pressure measured in the ESP.', NULL, 'never', 0, NULL, NULL, 'standard', 0, NULL, 0, 0, 0, 'proto+csv'),
  ('RouteLastUpdated', 107, 'Location', 'time', NULL, 'This field is broken and does not return data.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('RouteLine', 108, 'Location', 'string', NULL, 'A base64 encoded polyline of the active navigation route. To extract coordinates, decode the base64 and use Google''s polyline decoding algorithm. Precision 6 is used.', NULL, 'never', 0, NULL, NULL, 'trace', 1, '2024.26', 0, 0, 0, 'proto+csv'),
  ('MilesToArrival', 109, 'Location', 'real', 'drive_state.active_route_miles_to_arrival', 'The miles until arriving at the navigation destination. If no navigation destination is set, Invalid will be returned.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('MinutesToArrival', 110, 'Location', 'real', 'drive_state.active_route_minutes_to_arrival', 'The minutes until arriving at the navigation destination. If no navigation destination is set, Invalid will be returned.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('OriginLocation', 111, 'Location', 'Location', NULL, 'The coordinates of the current navigation route''s origin.', NULL, 'never', 0, NULL, NULL, 'location', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DestinationLocation', 112, 'Location', 'Location', 'drive_state.active_route_latitude, drive_state.active_route_longitude', 'The coordinates of the current navigation route''s destination. If no navigation destination is set, Invalid will be returned.', NULL, 'never', 0, NULL, NULL, 'location', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('CarType', 113, 'Vehicle Configuration', 'enum', 'vehicle_config.car_type', 'The model of the vehicle.', NULL, 'once', 1, '$vehicleInfo', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('Trim', 114, 'Vehicle Configuration', 'string', 'vehicle_config.trim_badging', 'The trim of the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('ExteriorColor', 115, 'Vehicle Configuration', 'string', 'vehicle_config.exterior_color', 'The exterior color of the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('RoofColor', 116, 'Vehicle Configuration', 'string', 'vehicle_config.roof_color', 'The color of the roof.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('ChargePort', 117, 'Charging', 'enum', 'vehicle_config.charge_port_type', 'The type of charge port installed.', 'ChargePortValue', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('ChargePortLatch', 118, 'Charging', 'enum', 'charge_state.charge_port_latch', 'Sensed state of the charge port latch. Early Model 3 vehicles will not latch in cold weather (below 5 degrees Celsius).', 'ChargePortLatchValue', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('Experimental_1', 119, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_2', 120, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_3', 121, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_4', 122, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('GuestModeEnabled', 123, 'Vehicle State', 'boolean', NULL, 'If guest mode is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('PinToDriveEnabled', 124, 'Safety', 'boolean', NULL, 'If pin to drive mode is enabled. Pin to drive requires entering a pin before shifting the vehicle out of park.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('PairedPhoneKeyAndKeyFobQty', 125, 'Vehicle State', 'integer', NULL, 'The number of phone keys and key fobs paired to the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('CruiseFollowDistance', 126, 'Safety', 'enum', NULL, 'The following distance selected in vehicle controls.', 'FollowDistance', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('AutomaticBlindSpotCamera', 127, 'Safety', 'boolean', NULL, 'Indicates whether the blind spot camera is enabled.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('BlindSpotCollisionWarningChime', 128, 'Safety', 'boolean', NULL, 'If the blindspot collision warning chime is enabled.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('SpeedLimitWarning', 129, 'Safety', 'enum', NULL, 'The speed assist level selected in vehicle settings.', 'SpeedAssistLevel', 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('ForwardCollisionWarning', 130, 'Safety', 'enum', NULL, 'The forward collision sensitivity selected in vehicle settings.', 'ForwardCollisionSensitivity', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('LaneDepartureAvoidance', 131, 'Safety', 'enum', NULL, 'The lane assist level selected in vehicle settings.', 'LaneAssistLevel', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('EmergencyLaneDepartureAvoidance', 132, 'Safety', 'boolean', NULL, 'If emergence lane keep assist is enabled.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('AutomaticEmergencyBrakingOff', 133, 'Safety', 'boolean', NULL, 'Indicates whether automatic emergency braking is disabled.', NULL, 'on_change', 1, '$vehicleState', NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('LifetimeEnergyGainedRegen', 134, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto'),
  ('DiStateF', 135, 'Powertrain', 'enum', NULL, 'Front drive inverter state.', 'DriveInverterState', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiStateREL', 136, 'Powertrain', 'enum', NULL, 'Rear Left drive inverter state.', 'DriveInverterState', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiStateRER', 137, 'Powertrain', 'enum', NULL, 'Rear Right drive inverter state.', 'DriveInverterState', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiHeatsinkTF', 138, 'Powertrain', 'real', NULL, 'Front drive inverter heatsink temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiHeatsinkTREL', 139, 'Powertrain', 'real', NULL, 'Rear left drive inverter heatsink temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiHeatsinkTRER', 140, 'Powertrain', 'real', NULL, 'Rear right drive inverter heatsink temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiAxleSpeedF', 141, 'Powertrain', 'real', NULL, 'Front drive inverter motor speed normalized at axle level.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiAxleSpeedREL', 142, 'Powertrain', 'real', NULL, 'Rear Left drive inverter motor speed normalized at axle level.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiAxleSpeedRER', 143, 'Powertrain', 'real', NULL, 'Rear Right drive inverter motor speed normalized at axle level.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiSlaveTorqueCmd', 144, 'Powertrain', 'real', NULL, 'Torque command to secondary drive unit.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiTorqueActualR', 145, 'Powertrain', 'real', NULL, 'Actual torque the rear drive unit is controlling to referred to the axle/wheel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiTorqueActualF', 146, 'Powertrain', 'real', NULL, 'Actual torque the front drive unit is controlling to referred to the axle/wheel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiTorqueActualREL', 147, 'Powertrain', 'real', NULL, 'Actual torque the rear left drive unit is controlling to referred to the axle/wheel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiTorqueActualRER', 148, 'Powertrain', 'real', NULL, 'Actual torque the rear right drive unit is controlling to referred to the axle/wheel.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiStatorTempF', 149, 'Powertrain', 'real', NULL, 'Front Drive Unit stator temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiStatorTempREL', 150, 'Powertrain', 'real', NULL, 'Rear Left Drive Unit stator temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiStatorTempRER', 151, 'Powertrain', 'real', NULL, 'Rear Right Drive Unit stator temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiVBatF', 152, 'Powertrain', 'real', NULL, 'Front drive inverter measured battery voltage.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiVBatREL', 153, 'Powertrain', 'real', NULL, 'Rear left drive inverter measured battery voltage.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiVBatRER', 154, 'Powertrain', 'real', NULL, 'Rear right drive inverter measured battery voltage.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiMotorCurrentF', 155, 'Powertrain', 'real', NULL, 'Front drive inverter motor current.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiMotorCurrentREL', 156, 'Powertrain', 'real', NULL, 'Rear Left drive inverter motor current.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiMotorCurrentRER', 157, 'Powertrain', 'real', NULL, 'Rear Right drive inverter motor current.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('EnergyRemaining', 158, 'Charging', 'real', NULL, 'The nominal energy remaining in the battery pack, measured in kWh.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('ServiceMode', 159, 'Vehicle State', 'boolean', 'vehicle_state.service_mode', 'If service mode is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('BMSState', 160, 'Charging', 'enum', NULL, 'BMS operating state.', 'BMSStateValue', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('GuestModeMobileAccessState', 161, 'Vehicle State', 'enum', NULL, 'The state of guest mode.', 'GuestModeMobileAccess', 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('Deprecated_1', 162, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 1, 0, 0, 'proto'),
  ('DestinationName', 163, 'Location', 'string', 'drive_state.active_route_destination', 'The name of the active navigation destination. If no destination is present, Invalid will be reported.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiInverterTR', 164, 'Powertrain', 'real', NULL, 'Rear drive inverter measured outlet temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiInverterTF', 165, 'Powertrain', 'real', NULL, 'Front drive inverter measured outlet temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiInverterTREL', 166, 'Powertrain', 'real', NULL, 'Rear left drive inverter measured outlet temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('DiInverterTRER', 167, 'Powertrain', 'real', NULL, 'Rear right drive inverter measured outlet temperature.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 0, 0, 'proto+csv'),
  ('Experimental_5', 168, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_6', 169, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_7', 170, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_8', 171, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_9', 172, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_10', 173, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_11', 174, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_12', 175, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_13', 176, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_14', 177, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('Experimental_15', 178, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.26', 0, 1, 0, 'proto'),
  ('DetailedChargeState', 179, 'Charging', 'enum', NULL, 'The detailed charge state, rather than ChargeState which provides little detail. This field is added in firmware version 2024.38.', 'DetailedChargeStateValue', 'never', 0, NULL, NULL, 'standard', 0, '2024.38', 0, 0, 0, 'proto+csv'),
  ('CabinOverheatProtectionMode', 180, 'Climate', 'enum', 'climate_state.cabin_overheat_protection', 'The mode of cabin overheat protection.', 'CabinOverheatProtectionModeState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.25', 0, 0, 0, 'proto+csv'),
  ('CabinOverheatProtectionTemperatureLimit', 181, 'Climate', 'enum', 'climate_state.cop_activation_temperature', 'The temperature limit of cabin overheat protection, represented as low, medium, or high.', 'ClimateOverheatProtectionTempLimit', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.25', 0, 0, 0, 'proto+csv'),
  ('CenterDisplay', 182, 'Vehicle State', 'enum', 'vehicle_state.center_display_state', 'The state of the center display.', 'DisplayState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.25', 0, 0, 0, 'proto+csv'),
  ('ChargePortDoorOpen', 183, 'Charging', 'boolean', 'charge_state.charge_port_door_open', 'Indicates whether the charge port door is open based only on the door potentiometer.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.25', 0, 0, 0, 'proto+csv'),
  ('ChargerVoltage', 184, 'Charging', 'real', 'charge_state.charger_voltage', 'RMS value of AC charger''s sensed input voltage. This field changes frequently, even when not charging. It is recommended to set minimum_delta, which is available on firmware version 2024.44.32 and later. Beginning with firmware version 2025.2.6, minimum_delta is set to 0.3 by default.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ChargingCableType', 185, 'Charging', 'enum', 'charge_state.conn_charge_cable', 'The type of charging cable connected to the vehicle. If no charging cable is present, Invalid will be returned.', 'CableType', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ClimateKeeperMode', 186, 'Climate', 'enum', 'climate_state.climate_keeper_mode', 'The climate keeper mode.', 'ClimateKeeperModeState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('DefrostForPreconditioning', 187, 'Climate', 'boolean', NULL, 'If the vehicle is defrosting due to preconditioning.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('DefrostMode', 188, 'Climate', 'enum', 'climate_state.defrost_mode', 'The state of the vehicle defrost.', 'DefrostModeState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('EfficiencyPackage', 189, 'Vehicle Configuration', 'string', 'vehicle_config.efficiency_package', 'The efficiency package of the vehicle. This is returned as a string since possible values vary by vehicle model and platform.', NULL, 'once', 1, '$vehicleInfo', NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('EstimatedHoursToChargeTermination', 190, 'Charging', 'real', NULL, 'The number of hours until reaching the desired state of charge. Desired state of charge is defined by ChargeLimitSoc.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('EuropeVehicle', 191, 'Vehicle Configuration', 'boolean', 'vehicle_config.eu_vehicle', 'If this vehicle is classified as a Europe vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ExpectedEnergyPercentAtTripArrival', 192, 'Charging', 'integer', 'drive_state.active_route_energy_at_arrival', 'The expected energy percentage upon arriving at destination. If no navigation destination is set, Invalid will be returned.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('FastChargerType', 193, 'Charging', 'enum', 'charge_state.fast_charger_type', 'The type of fast charger connected to the vehicle.', 'FastCharger', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HomelinkDeviceCount', 194, 'Vehicle State', 'integer', 'vehicle_state.homelink_nearby', 'The number of nearby homelink devices.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HomelinkNearby', 195, 'Vehicle State', 'boolean', 'vehicle_state.homelink_device_count', 'If a homelink device is nearby.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacACEnabled', 196, 'Climate', 'boolean', NULL, 'If AC is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacAutoMode', 197, 'Climate', 'enum', 'climate_state.hvac_auto_request', 'The state of HVAC auto mode.', 'HvacAutoModeState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacFanSpeed', 198, 'Climate', 'integer', NULL, 'The HVAC fan speed.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacFanStatus', 199, 'Climate', 'integer', 'climate_state.fan_status', 'Cabin airflow blower set speed segment.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacLeftTemperatureRequest', 200, 'Climate', 'real', 'climate_state.driver_temp_setting, climate_state.passenger_temp_setting', 'The requested temperature for the left front side of the vehicle. Reported in celsius. This differs slightly from the equivalent vehicle_data fields as it is based on the side of the vehicle instead of passenger/driver.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacPower', 201, 'Climate', 'enum', 'climate_state.is_climate_on', 'The power state of the HVAC system.', 'HvacPowerState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacRightTemperatureRequest', 202, 'Climate', 'real', 'climate_state.driver_temp_setting, climate_state.passenger_temp_setting', 'The requested temperature for the right front side of the vehicle. Reported in celsius. This differs slightly from the equivalent vehicle_data fields as it is based on the side of the vehicle instead of passenger/driver.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacSteeringWheelHeatAuto', 203, 'Climate', 'boolean', 'climate_state.auto_steering_wheel_heat', 'If the steering wheel heat is set to auto.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('HvacSteeringWheelHeatLevel', 204, 'Climate', 'integer', 'climate_state.steering_wheel_heat_level', 'The level of steering wheel heat.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('OffroadLightbarPresent', 205, 'Vehicle Configuration', 'boolean', NULL, 'Report whether the offroad light bar is detected.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('PowershareHoursLeft', 206, 'Charging', 'integer', NULL, 'The number of hours remaining through Powershare.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('PowershareInstantaneousPowerKW', 207, 'Charging', 'real', NULL, 'Displays the current AC real power output from Power Conversion System 2 (PCS2) in Vehicle-to-Everything (V2X) mode. A positive value indicates battery discharge (power flowing out of the battery).', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('PowershareStatus', 208, 'Charging', 'enum', NULL, 'The state of Powershare.', 'PowershareState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('PowershareStopReason', 209, 'Charging', 'enum', NULL, 'The reason Powershare has stopped.', 'PowershareStopReasonStatus', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('PowershareType', 210, 'Charging', 'enum', NULL, 'The type of Powershare currently active.', 'PowershareTypeStatus', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('RearDisplayHvacEnabled', 211, 'Climate', 'boolean', NULL, 'If HVAC is enabled on the rear display.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('RearSeatHeaters', 212, 'Vehicle Configuration', 'string', 'vehicle_config.rear_seat_heaters', 'The rear seat heater package installed on the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('RemoteStartEnabled', 213, 'Vehicle Configuration', 'boolean', 'vehicle_state.remote_start_enabled', 'If the vehicle is being driven without a physical key.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('RightHandDrive', 214, 'Vehicle Configuration', 'boolean', 'vehicle_config.rhd', 'If the vehicle is a right hand drive vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('RouteTrafficMinutesDelay', 215, 'Driving', 'real', 'drive_state.active_route_traffic_minutes_delay', 'The number of minutes delay on the active navigation route.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SoftwareUpdateDownloadPercentComplete', 216, 'Vehicle State', 'integer', 'vehicle_state.software_update.download_perc', 'The percent of the software update that has been downloaded. Note: during the download of one software update, this value will go from 0-100% multiple times.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SoftwareUpdateExpectedDurationMinutes', 217, 'Vehicle State', 'integer', 'vehicle_state.software_update.expected_duration_sec', 'The number of minutes a software update is estimated to take.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SoftwareUpdateInstallationPercentComplete', 218, 'Vehicle State', 'integer', 'vehicle_state.software_update.install_perc', 'The percent a software update has finished installing. Vehicles will not remain connected to Fleet Telemetry for the entire duration of a software update.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SoftwareUpdateScheduledStartTime', 219, 'Vehicle State', 'timestamp', 'vehicle_state.software_update.scheduled_time_ms', 'The time a software update is scheduled to begin installing. Timestamp fields report incorrectly. Treating the reported value as Pacific Time will yield the date and time in the vehicle''s timezone.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SoftwareUpdateVersion', 220, 'Vehicle State', 'string', 'vehicle_state.software_update.version', 'The version of an available software update.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('TonneauOpenPercent', 221, 'Vehicle State', 'real', NULL, 'The percent the Cybertruck''s tonneau cover is open.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('TonneauPosition', 222, 'Vehicle State', 'enum', NULL, 'The state of the Cybertruck''s tonneau.', 'TonneauPositionState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('TonneauTentMode', 223, 'Vehicle State', 'enum', NULL, 'State of the Cybertruck''s tonneau in relationship to tent mode.', 'TonneauTentModeState', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('TpmsHardWarnings', 224, 'Service', 'enum', 'vehicle_state.tpms_hard_warning_fl, vehicle_state.tpms_hard_warning_fr, vehicle_state.tpms_hard_warning_rl, vehicle_state.tpms_hard_warning_rr', 'Indicates a tire''s pressure needs to be inspected and is severely out of nominal range.', 'TireLocation', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('TpmsSoftWarnings', 225, 'Service', 'enum', 'vehicle_state.tpms_soft_warning_fl, vehicle_state.tpms_soft_warning_fr, vehicle_state.tpms_soft_warning_rl, vehicle_state.tpms_soft_warning_rr', 'Indicates a tire''s pressure needs to be inspected and is slightly out of nominal range.', 'TireLocation', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ValetModeEnabled', 226, 'Vehicle State', 'boolean', 'vehicle_state.valet_mode', 'If valet mode is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('WheelType', 227, 'Vehicle Configuration', 'string', 'vehicle_config.wheel_type', 'The type of wheel installed on the vehicle.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('WiperHeatEnabled', 228, 'Climate', 'boolean', 'climate_state.wiper_blade_heater', 'If the wiper heater are turned on.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('LocatedAtHome', 229, 'Location', 'boolean', NULL, 'If the vehicle is located at the active driver profile’s saved home location.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('LocatedAtWork', 230, 'Location', 'boolean', NULL, 'If the vehicle is located at the active driver profile’s saved work location.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('LocatedAtFavorite', 231, 'Location', 'boolean', NULL, 'If the vehicle is located at a favorite location of the active driver profile.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SettingDistanceUnit', 232, 'User Preference', 'enum', 'gui_settings.gui_distance_units', 'The units the vehicle uses when displaying distance.', 'DistanceUnit', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SettingTemperatureUnit', 233, 'User Preference', 'enum', 'gui_settings.gui_temperature_units', 'The preferred unit for displaying temperature data.', 'TemperatureUnit', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('Setting24HourTime', 234, 'User Preference', 'boolean', 'gui_settings.gui_24_hour_time', 'If 24 hour time is preferred for displaying time.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SettingTirePressureUnit', 235, 'User Preference', 'enum', 'gui_settings.gui_tirepressure_units', 'The preferred unit for displaying pressure data.', 'PressureUnit', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('SettingChargeUnit', 236, 'User Preference', 'enum', 'gui_settings.gui_charge_rate_units', 'The preferred unit for displaying charge range.', 'ChargeUnitPreference', 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ClimateSeatCoolingFrontLeft', 237, 'Climate', 'integer', 'climate_state.seat_fan_front_left', 'The seat cooling level requested by the front left seat.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('ClimateSeatCoolingFrontRight', 238, 'Climate', 'integer', 'climate_state.seat_fan_front_right', 'The seat cooling level requested by the front right seat.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2024.44.32', 0, 0, 0, 'proto+csv'),
  ('LightsHazardsActive', 239, 'Vehicle State', 'boolean', NULL, 'If the vehicle''s hazard lights are activated.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('LightsTurnSignal', 240, 'Vehicle State', 'enum', NULL, 'The state of turn signals. Left, right, both, none.', 'TurnSignalState', 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('LightsHighBeams', 241, 'Vehicle State', 'boolean', NULL, 'If the vehicle''s high beams are activated.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaPlaybackStatus', 242, 'Media', 'enum', 'media_info.media_playback_status', 'The state of media playback.', 'MediaStatus', 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaPlaybackSource', 243, 'Media', 'string', 'media_info.now_playing_source', 'The source actively being used for playing media.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaAudioVolume', 244, 'Media', 'real', 'media_info.audio_volume', 'The volume of in-cabin audio measured from 0-11.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingDuration', 245, 'Media', 'integer', 'media_info.now_playing_duration', 'The length of the current track measured in milliseconds. For radio stations which do not have a duration, 18000000 is reported.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingElapsed', 246, 'Media', 'integer', 'media_info.now_playing_elapsed', 'The playback position in the current track, measured in milliseconds. The value returned while listening to a radio station may be nonsensical.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingArtist', 247, 'Media', 'string', 'media_info.now_playing_artist', 'The artist of the current track.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingTitle', 248, 'Media', 'string', 'media_info.now_playing_title', 'The title of the current track.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingAlbum', 249, 'Media', 'string', 'media_info.now_playing_album', 'The album of the current track.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaNowPlayingStation', 250, 'Media', 'string', 'media_info.now_playing_station', 'The station playing media.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaAudioVolumeIncrement', 251, 'Media', 'real', 'media_info.audio_volume_increment', 'The size of volume increments or decrements.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('MediaAudioVolumeMax', 252, 'Media', 'real', 'media_info.audio_volume_max', 'The maximum volume available to be selected.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('SunroofInstalled', 253, 'Vehicle Configuration', 'enum', 'vehicle_config.sun_roof_installed', 'The installation state of a sunroof.', 'SunroofInstalledState', 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('SeatVentEnabled', 254, 'Climate', 'boolean', NULL, 'If front seat ventilation is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('RearDefrostEnabled', 255, 'Climate', 'boolean', 'climate_state.is_rear_defroster_on', 'If rear defrost is enabled.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('ChargeRateMilePerHour', 256, 'Charging', 'real', 'charge_state.charge_rate', 'The number of miles being added per hour of charging, given the current charge rate.', NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 0, 0, 0, 'proto+csv'),
  ('Deprecated_3', 257, 'Uncategorised', 'internal', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2025.2.6', 1, 0, 0, 'proto'),
  ('MilesSinceReset', 258, 'Safety', 'real', NULL, 'The total number of miles driven since the Self-Driving statistics were reset. A reset may occur for certain software updates, car computer replacement, factory reset, or other triggers. This field is only available on HW4 vehicles running firmware version 2025.44.25.5 or later.', NULL, 'event', 1, 'vehicleState', 1.0, 'standard', 0, '2025.44.25.5', 0, 0, 0, 'proto+csv'),
  ('SelfDrivingMilesSinceReset', 259, 'Safety', 'real', NULL, 'The total number of miles driven using Full Self-Driving since the Self-Driving statistics were reset. A reset may occur for certain software updates, car computer replacement, factory reset, or other triggers. This field requires minimum_delta to be explicitly set to a value >= 1 and is only available on HW4 vehicles running firmware version 2025.44.25.5 or later.', NULL, 'event', 1, 'vehicleState', 1.0, 'standard', 0, '2025.44.25.5', 0, 0, 0, 'proto+csv'),
  ('GpsAccuracyMeters', 260, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('LifetimeEnergyChargedKwh', 261, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('BrickSocMinPercent', 262, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('NominalFullPackEnergyKwh', 263, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('GradeEstimatePercent', 264, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('MaxSpeedToReachDestinationMph', 265, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('SoftwareUpdateAvailable', 266, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('SoftwareUpdateInProgress', 267, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('RemoteStartActive', 268, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 0, 'proto'),
  ('SemiCruiseSpeedLimitMph', 269, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 1, 'proto'),
  ('Cabin12vPortKeepOn', 270, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 1, 'proto'),
  ('Cabin48vPortKeepOn', 271, 'Uncategorised', 'unknown', NULL, NULL, NULL, 'never', 0, NULL, NULL, 'standard', 0, '2026.32', 0, 0, 1, 'proto');

INSERT INTO tesla_field_enum_def (enum_name, description, value_count) VALUES
  ('BMSStateValue', NULL, 11),
  ('BuckleStatus', NULL, 4),
  ('CabinOverheatProtectionModeState', NULL, 4),
  ('CabinPortKeepOnState', NULL, 3),
  ('CableType', NULL, 6),
  ('CarTypeValue', NULL, 7),
  ('ChargePortLatchValue', NULL, 5),
  ('ChargePortValue', NULL, 5),
  ('ChargeUnitPreference', NULL, 3),
  ('ChargingState', NULL, 7),
  ('ClimateKeeperModeState', NULL, 5),
  ('ClimateOverheatProtectionTempLimit', NULL, 4),
  ('DefrostModeState', NULL, 5),
  ('DetailedChargeStateValue', NULL, 7),
  ('DisplayState', NULL, 11),
  ('DistanceUnit', NULL, 3),
  ('DriveInverterState', NULL, 6),
  ('FastCharger', NULL, 9),
  ('FollowDistance', NULL, 8),
  ('ForwardCollisionSensitivity', NULL, 5),
  ('GuestModeMobileAccess', NULL, 19),
  ('HvacAutoModeState', NULL, 3),
  ('HvacPowerState', NULL, 5),
  ('HvilStatus', NULL, 3),
  ('LaneAssistLevel', NULL, 4),
  ('MediaStatus', NULL, 4),
  ('PowershareState', NULL, 7),
  ('PowershareStopReasonStatus', NULL, 8),
  ('PowershareTypeStatus', NULL, 4),
  ('PressureUnit', NULL, 3),
  ('ScheduledChargingModeValue', NULL, 4),
  ('SeatFoldPosition', NULL, 6),
  ('SentryModeState', NULL, 7),
  ('ShiftState', NULL, 7),
  ('SpeedAssistLevel', NULL, 4),
  ('SunroofInstalledState', NULL, 4),
  ('TemperatureUnit', NULL, 3),
  ('TonneauPositionState', NULL, 5),
  ('TonneauTentModeState', NULL, 5),
  ('TractorAirStatus', NULL, 7),
  ('TrailerAirStatus', NULL, 8),
  ('TurnSignalState', NULL, 5),
  ('WindowState', NULL, 4);

INSERT INTO tesla_field_enum_value (enum_name, value_int, value_label) VALUES
  ('BMSStateValue', 0, 'BMSStateUnknown'),
  ('BMSStateValue', 1, 'BMSStateStandby'),
  ('BMSStateValue', 2, 'BMSStateDrive'),
  ('BMSStateValue', 3, 'BMSStateSupport'),
  ('BMSStateValue', 4, 'BMSStateCharge'),
  ('BMSStateValue', 5, 'BMSStateFEIM'),
  ('BMSStateValue', 6, 'BMSStateClearFault'),
  ('BMSStateValue', 7, 'BMSStateFault'),
  ('BMSStateValue', 8, 'BMSStateWeld'),
  ('BMSStateValue', 9, 'BMSStateTest'),
  ('BMSStateValue', 10, 'BMSStateSNA'),
  ('BuckleStatus', 0, 'BuckleStatusUnknown'),
  ('BuckleStatus', 1, 'BuckleStatusUnlatched'),
  ('BuckleStatus', 2, 'BuckleStatusLatched'),
  ('BuckleStatus', 3, 'BuckleStatusFaulted'),
  ('CabinOverheatProtectionModeState', 0, 'CabinOverheatProtectionModeStateUnknown'),
  ('CabinOverheatProtectionModeState', 1, 'CabinOverheatProtectionModeStateOff'),
  ('CabinOverheatProtectionModeState', 2, 'CabinOverheatProtectionModeStateOn'),
  ('CabinOverheatProtectionModeState', 3, 'CabinOverheatProtectionModeStateFanOnly'),
  ('CabinPortKeepOnState', 0, 'CabinPortKeepOnStateUnknown'),
  ('CabinPortKeepOnState', 1, 'CabinPortKeepOnStateOff'),
  ('CabinPortKeepOnState', 2, 'CabinPortKeepOnStateOn'),
  ('CableType', 0, 'CableTypeUnknown'),
  ('CableType', 1, 'CableTypeIEC'),
  ('CableType', 2, 'CableTypeSAE'),
  ('CableType', 3, 'CableTypeGB_AC'),
  ('CableType', 4, 'CableTypeGB_DC'),
  ('CableType', 5, 'CableTypeSNA'),
  ('CarTypeValue', 0, 'CarTypeUnknown'),
  ('CarTypeValue', 1, 'CarTypeModelS'),
  ('CarTypeValue', 2, 'CarTypeModelX'),
  ('CarTypeValue', 3, 'CarTypeModel3'),
  ('CarTypeValue', 4, 'CarTypeModelY'),
  ('CarTypeValue', 5, 'CarTypeSemiTruck'),
  ('CarTypeValue', 6, 'CarTypeCybertruck'),
  ('ChargePortLatchValue', 0, 'ChargePortLatchUnknown'),
  ('ChargePortLatchValue', 1, 'ChargePortLatchSNA'),
  ('ChargePortLatchValue', 2, 'ChargePortLatchDisengaged'),
  ('ChargePortLatchValue', 3, 'ChargePortLatchEngaged'),
  ('ChargePortLatchValue', 4, 'ChargePortLatchBlocking'),
  ('ChargePortValue', 0, 'ChargePortUnknown'),
  ('ChargePortValue', 1, 'ChargePortUS'),
  ('ChargePortValue', 2, 'ChargePortEU'),
  ('ChargePortValue', 3, 'ChargePortGB'),
  ('ChargePortValue', 4, 'ChargePortCCS'),
  ('ChargeUnitPreference', 0, 'ChargeUnitUnknown'),
  ('ChargeUnitPreference', 1, 'ChargeUnitDistance'),
  ('ChargeUnitPreference', 2, 'ChargeUnitPercent'),
  ('ChargingState', 0, 'ChargeStateUnknown'),
  ('ChargingState', 1, 'ChargeStateDisconnected'),
  ('ChargingState', 2, 'ChargeStateNoPower'),
  ('ChargingState', 3, 'ChargeStateStarting'),
  ('ChargingState', 4, 'ChargeStateCharging'),
  ('ChargingState', 5, 'ChargeStateComplete'),
  ('ChargingState', 6, 'ChargeStateStopped'),
  ('ClimateKeeperModeState', 0, 'ClimateKeeperModeStateUnknown'),
  ('ClimateKeeperModeState', 1, 'ClimateKeeperModeStateOff'),
  ('ClimateKeeperModeState', 2, 'ClimateKeeperModeStateOn'),
  ('ClimateKeeperModeState', 3, 'ClimateKeeperModeStateDog'),
  ('ClimateKeeperModeState', 4, 'ClimateKeeperModeStateParty'),
  ('ClimateOverheatProtectionTempLimit', 0, 'ClimateOverheatProtectionTempLimitUnknown'),
  ('ClimateOverheatProtectionTempLimit', 1, 'ClimateOverheatProtectionTempLimitHigh'),
  ('ClimateOverheatProtectionTempLimit', 2, 'ClimateOverheatProtectionTempLimitMedium'),
  ('ClimateOverheatProtectionTempLimit', 3, 'ClimateOverheatProtectionTempLimitLow'),
  ('DefrostModeState', 0, 'DefrostModeStateUnknown'),
  ('DefrostModeState', 1, 'DefrostModeStateOff'),
  ('DefrostModeState', 2, 'DefrostModeStateNormal'),
  ('DefrostModeState', 3, 'DefrostModeStateMax'),
  ('DefrostModeState', 4, 'DefrostModeStateAutoDefog'),
  ('DetailedChargeStateValue', 0, 'DetailedChargeStateUnknown'),
  ('DetailedChargeStateValue', 1, 'DetailedChargeStateDisconnected'),
  ('DetailedChargeStateValue', 2, 'DetailedChargeStateNoPower'),
  ('DetailedChargeStateValue', 3, 'DetailedChargeStateStarting'),
  ('DetailedChargeStateValue', 4, 'DetailedChargeStateCharging'),
  ('DetailedChargeStateValue', 5, 'DetailedChargeStateComplete'),
  ('DetailedChargeStateValue', 6, 'DetailedChargeStateStopped'),
  ('DisplayState', 0, 'DisplayStateUnknown'),
  ('DisplayState', 1, 'DisplayStateOff'),
  ('DisplayState', 2, 'DisplayStateDim'),
  ('DisplayState', 3, 'DisplayStateAccessory'),
  ('DisplayState', 4, 'DisplayStateOn'),
  ('DisplayState', 5, 'DisplayStateDriving'),
  ('DisplayState', 6, 'DisplayStateCharging'),
  ('DisplayState', 7, 'DisplayStateLock'),
  ('DisplayState', 8, 'DisplayStateSentry'),
  ('DisplayState', 9, 'DisplayStateDog'),
  ('DisplayState', 10, 'DisplayStateEntertainment'),
  ('DistanceUnit', 0, 'DistanceUnitUnknown'),
  ('DistanceUnit', 1, 'DistanceUnitMiles'),
  ('DistanceUnit', 2, 'DistanceUnitKilometers'),
  ('DriveInverterState', 0, 'DriveInverterStateUnknown'),
  ('DriveInverterState', 1, 'DriveInverterStateUnavailable'),
  ('DriveInverterState', 2, 'DriveInverterStateStandby'),
  ('DriveInverterState', 3, 'DriveInverterStateFault'),
  ('DriveInverterState', 4, 'DriveInverterStateAbort'),
  ('DriveInverterState', 5, 'DriveInverterStateEnable'),
  ('FastCharger', 0, 'FastChargerUnknown'),
  ('FastCharger', 1, 'FastChargerSupercharger'),
  ('FastCharger', 2, 'FastChargerCHAdeMO'),
  ('FastCharger', 3, 'FastChargerGB'),
  ('FastCharger', 4, 'FastChargerACSingleWireCAN'),
  ('FastCharger', 5, 'FastChargerCombo'),
  ('FastCharger', 6, 'FastChargerMCSingleWireCAN'),
  ('FastCharger', 7, 'FastChargerOther'),
  ('FastCharger', 8, 'FastChargerSNA'),
  ('FollowDistance', 0, 'FollowDistanceUnknown'),
  ('FollowDistance', 1, 'FollowDistance1'),
  ('FollowDistance', 2, 'FollowDistance2'),
  ('FollowDistance', 3, 'FollowDistance3'),
  ('FollowDistance', 4, 'FollowDistance4'),
  ('FollowDistance', 5, 'FollowDistance5'),
  ('FollowDistance', 6, 'FollowDistance6'),
  ('FollowDistance', 7, 'FollowDistance7'),
  ('ForwardCollisionSensitivity', 0, 'ForwardCollisionSensitivityUnknown'),
  ('ForwardCollisionSensitivity', 1, 'ForwardCollisionSensitivityOff'),
  ('ForwardCollisionSensitivity', 2, 'ForwardCollisionSensitivityLate'),
  ('ForwardCollisionSensitivity', 3, 'ForwardCollisionSensitivityAverage'),
  ('ForwardCollisionSensitivity', 4, 'ForwardCollisionSensitivityEarly'),
  ('GuestModeMobileAccess', 0, 'GuestModeMobileAccessUnknown'),
  ('GuestModeMobileAccess', 1, 'GuestModeMobileAccessInit'),
  ('GuestModeMobileAccess', 2, 'GuestModeMobileAccessNotAuthenticated'),
  ('GuestModeMobileAccess', 3, 'GuestModeMobileAccessAuthenticated'),
  ('GuestModeMobileAccess', 4, 'GuestModeMobileAccessAbortedDriving'),
  ('GuestModeMobileAccess', 5, 'GuestModeMobileAccessAbortedUsingRemoteStart'),
  ('GuestModeMobileAccess', 6, 'GuestModeMobileAccessAbortedUsingBLEKeys'),
  ('GuestModeMobileAccess', 7, 'GuestModeMobileAccessAbortedValetMode'),
  ('GuestModeMobileAccess', 8, 'GuestModeMobileAccessAbortedGuestModeOff'),
  ('GuestModeMobileAccess', 9, 'GuestModeMobileAccessAbortedDriveAuthTimeExceeded'),
  ('GuestModeMobileAccess', 10, 'GuestModeMobileAccessAbortedNoDataReceived'),
  ('GuestModeMobileAccess', 11, 'GuestModeMobileAccessRequestingFromMothership'),
  ('GuestModeMobileAccess', 12, 'GuestModeMobileAccessRequestingFromAuthD'),
  ('GuestModeMobileAccess', 13, 'GuestModeMobileAccessAbortedFetchFailed'),
  ('GuestModeMobileAccess', 14, 'GuestModeMobileAccessAbortedBadDataReceived'),
  ('GuestModeMobileAccess', 15, 'GuestModeMobileAccessShowingQRCode'),
  ('GuestModeMobileAccess', 16, 'GuestModeMobileAccessSwipedAway'),
  ('GuestModeMobileAccess', 17, 'GuestModeMobileAccessDismissedQRCodeExpired'),
  ('GuestModeMobileAccess', 18, 'GuestModeMobileAccessSucceededPairedNewBLEKey'),
  ('HvacAutoModeState', 0, 'HvacAutoModeStateUnknown'),
  ('HvacAutoModeState', 1, 'HvacAutoModeStateOn'),
  ('HvacAutoModeState', 2, 'HvacAutoModeStateOverride'),
  ('HvacPowerState', 0, 'HvacPowerStateUnknown'),
  ('HvacPowerState', 1, 'HvacPowerStateOff'),
  ('HvacPowerState', 2, 'HvacPowerStateOn'),
  ('HvacPowerState', 3, 'HvacPowerStatePrecondition'),
  ('HvacPowerState', 4, 'HvacPowerStateOverheatProtect'),
  ('HvilStatus', 0, 'HvilStatusUnknown'),
  ('HvilStatus', 1, 'HvilStatusFault'),
  ('HvilStatus', 2, 'HvilStatusOK'),
  ('LaneAssistLevel', 0, 'LaneAssistLevelUnknown'),
  ('LaneAssistLevel', 1, 'LaneAssistLevelNone'),
  ('LaneAssistLevel', 2, 'LaneAssistLevelWarning'),
  ('LaneAssistLevel', 3, 'LaneAssistLevelAssist'),
  ('MediaStatus', 0, 'MediaStatusUnknown'),
  ('MediaStatus', 1, 'MediaStatusStopped'),
  ('MediaStatus', 2, 'MediaStatusPlaying'),
  ('MediaStatus', 3, 'MediaStatusPaused'),
  ('PowershareState', 0, 'PowershareStateUnknown'),
  ('PowershareState', 1, 'PowershareStateInactive'),
  ('PowershareState', 2, 'PowershareStateHandshaking'),
  ('PowershareState', 3, 'PowershareStateInit'),
  ('PowershareState', 4, 'PowershareStateEnabled'),
  ('PowershareState', 5, 'PowershareStateEnabledReconnectingSoon'),
  ('PowershareState', 6, 'PowershareStateStopped'),
  ('PowershareStopReasonStatus', 0, 'PowershareStopReasonStatusUnknown'),
  ('PowershareStopReasonStatus', 1, 'PowershareStopReasonStatusNone'),
  ('PowershareStopReasonStatus', 2, 'PowershareStopReasonStatusSOCTooLow'),
  ('PowershareStopReasonStatus', 3, 'PowershareStopReasonStatusRetry'),
  ('PowershareStopReasonStatus', 4, 'PowershareStopReasonStatusFault'),
  ('PowershareStopReasonStatus', 5, 'PowershareStopReasonStatusUser'),
  ('PowershareStopReasonStatus', 6, 'PowershareStopReasonStatusReconnecting'),
  ('PowershareStopReasonStatus', 7, 'PowershareStopReasonStatusAuthentication'),
  ('PowershareTypeStatus', 0, 'PowershareTypeStatusUnknown'),
  ('PowershareTypeStatus', 1, 'PowershareTypeStatusNone'),
  ('PowershareTypeStatus', 2, 'PowershareTypeStatusLoad'),
  ('PowershareTypeStatus', 3, 'PowershareTypeStatusHome'),
  ('PressureUnit', 0, 'PressureUnitUnknown'),
  ('PressureUnit', 1, 'PressureUnitPsi'),
  ('PressureUnit', 2, 'PressureUnitBar'),
  ('ScheduledChargingModeValue', 0, 'ScheduledChargingModeUnknown'),
  ('ScheduledChargingModeValue', 1, 'ScheduledChargingModeOff'),
  ('ScheduledChargingModeValue', 2, 'ScheduledChargingModeStartAt'),
  ('ScheduledChargingModeValue', 3, 'ScheduledChargingModeDepartBy'),
  ('SeatFoldPosition', 0, 'SeatFoldPositionUnknown'),
  ('SeatFoldPosition', 1, 'SeatFoldPositionSNA'),
  ('SeatFoldPosition', 2, 'SeatFoldPositionFaulted'),
  ('SeatFoldPosition', 3, 'SeatFoldPositionNotConfigured'),
  ('SeatFoldPosition', 4, 'SeatFoldPositionFolded'),
  ('SeatFoldPosition', 5, 'SeatFoldPositionUnfolded'),
  ('SentryModeState', 0, 'SentryModeStateUnknown'),
  ('SentryModeState', 1, 'SentryModeStateOff'),
  ('SentryModeState', 2, 'SentryModeStateIdle'),
  ('SentryModeState', 3, 'SentryModeStateArmed'),
  ('SentryModeState', 4, 'SentryModeStateAware'),
  ('SentryModeState', 5, 'SentryModeStatePanic'),
  ('SentryModeState', 6, 'SentryModeStateQuiet'),
  ('ShiftState', 0, 'ShiftStateUnknown'),
  ('ShiftState', 1, 'ShiftStateInvalid'),
  ('ShiftState', 2, 'ShiftStateP'),
  ('ShiftState', 3, 'ShiftStateR'),
  ('ShiftState', 4, 'ShiftStateN'),
  ('ShiftState', 5, 'ShiftStateD'),
  ('ShiftState', 6, 'ShiftStateSNA'),
  ('SpeedAssistLevel', 0, 'SpeedAssistLevelUnknown'),
  ('SpeedAssistLevel', 1, 'SpeedAssistLevelNone'),
  ('SpeedAssistLevel', 2, 'SpeedAssistLevelDisplay'),
  ('SpeedAssistLevel', 3, 'SpeedAssistLevelChime'),
  ('SunroofInstalledState', 0, 'SunroofInstalledStateUnknown'),
  ('SunroofInstalledState', 1, 'SunroofInstalledStateNotInstalled'),
  ('SunroofInstalledState', 2, 'SunroofInstalledStateGen1Installed'),
  ('SunroofInstalledState', 3, 'SunroofInstalledStateGen2Installed'),
  ('TemperatureUnit', 0, 'TemperatureUnitUnknown'),
  ('TemperatureUnit', 1, 'TemperatureUnitFahrenheit'),
  ('TemperatureUnit', 2, 'TemperatureUnitCelsius'),
  ('TonneauPositionState', 0, 'TonneauPositionStateUnknown'),
  ('TonneauPositionState', 1, 'TonneauPositionStateInvalid'),
  ('TonneauPositionState', 2, 'TonneauPositionStateClosed'),
  ('TonneauPositionState', 3, 'TonneauPositionStatePartiallyOpen'),
  ('TonneauPositionState', 4, 'TonneauPositionStateFullyOpen'),
  ('TonneauTentModeState', 0, 'TonneauTentModeStateUnknown'),
  ('TonneauTentModeState', 1, 'TonneauTentModeStateInactive'),
  ('TonneauTentModeState', 2, 'TonneauTentModeStateMoving'),
  ('TonneauTentModeState', 3, 'TonneauTentModeStateFailed'),
  ('TonneauTentModeState', 4, 'TonneauTentModeStateActive'),
  ('TractorAirStatus', 0, 'TractorAirStatusUnknown'),
  ('TractorAirStatus', 1, 'TractorAirStatusNotAvailable'),
  ('TractorAirStatus', 2, 'TractorAirStatusError'),
  ('TractorAirStatus', 3, 'TractorAirStatusCharged'),
  ('TractorAirStatus', 4, 'TractorAirStatusBuildingPressureIntermediate'),
  ('TractorAirStatus', 5, 'TractorAirStatusExhaustingPressureIntermediate'),
  ('TractorAirStatus', 6, 'TractorAirStatusExhausted'),
  ('TrailerAirStatus', 0, 'TrailerAirStatusUnknown'),
  ('TrailerAirStatus', 1, 'TrailerAirStatusSNA'),
  ('TrailerAirStatus', 2, 'TrailerAirStatusInvalid'),
  ('TrailerAirStatus', 3, 'TrailerAirStatusBobtailMode'),
  ('TrailerAirStatus', 4, 'TrailerAirStatusCharged'),
  ('TrailerAirStatus', 5, 'TrailerAirStatusBuildingPressureIntermediate'),
  ('TrailerAirStatus', 6, 'TrailerAirStatusExhaustingPressureIntermediate'),
  ('TrailerAirStatus', 7, 'TrailerAirStatusExhausted'),
  ('TurnSignalState', 0, 'TurnSignalStateUnknown'),
  ('TurnSignalState', 1, 'TurnSignalStateOff'),
  ('TurnSignalState', 2, 'TurnSignalStateLeft'),
  ('TurnSignalState', 3, 'TurnSignalStateRight'),
  ('TurnSignalState', 4, 'TurnSignalStateBoth'),
  ('WindowState', 0, 'WindowStateUnknown'),
  ('WindowState', 1, 'WindowStateClosed'),
  ('WindowState', 2, 'WindowStatePartiallyOpen'),
  ('WindowState', 3, 'WindowStateOpened');

INSERT OR REPLACE INTO tesla_catalog_load (catalog_name, source_name, source_sha256,
  source_rows, loaded_rows, loaded_at, loader_version) VALUES
  ('field', 'vehicle_data.proto + fleet_streaming_fields.csv',
   '5cd3a9c526f0cddda75cfac3c37e82e51e333f8dd49b0c6beeffab212bf43edf', 239, 272, '2026-10-02T00:00:00Z', 'build-catalog.py/1.0.0');
