-- Seed the complete Fleet API endpoint registry (FRS-010 F03-R05/R06).
--
-- GENERATED FILE - do not edit by hand.
-- Regenerate with: python3 scripts/build-endpoints.py --docs <dir>
--
-- source sha256 300372c2718cc32edbdc3b682bfdbde646d408354272da48cf1794bd5202973a
-- endpoints     107
--
-- Families not enabled at MVP are seeded with enabled = 0 and retained:
-- vehicle_command, energy_command, enterprise. Enabling one later is a
-- flag change rather than a migration.

DELETE FROM tesla_endpoint_catalog;

INSERT INTO tesla_endpoint_catalog (endpoint_key, family, method, path_template,
  scope, requires_auth, is_command, enabled, description, doc_url) VALUES
  ('energy_command.energy_sites.site.backup.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/backup', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('energy.energy_sites.site.calendar_history.get', 'energy', 'GET', '/api/1/energy_sites/{energy_site_id}/calendar_history', 'energy_device_data', 'user', 0, 1, NULL, NULL),
  ('energy_command.energy_sites.site.grid_import_export.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/grid_import_export', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('energy.energy_sites.site.live_status.get', 'energy', 'GET', '/api/1/energy_sites/{energy_site_id}/live_status', 'energy_device_data', 'user', 0, 1, NULL, NULL),
  ('energy_command.energy_sites.site.off_grid_vehicle_charging_reserve.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/off_grid_vehicle_charging_reserve', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('energy_command.energy_sites.site.operation.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/operation', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('energy.energy_sites.site.site_info.get', 'energy', 'GET', '/api/1/energy_sites/{energy_site_id}/site_info', 'energy_device_data', 'user', 0, 1, NULL, NULL),
  ('energy_command.energy_sites.site.storm_mode.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/storm_mode', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('energy.energy_sites.site.telemetry_history.get', 'energy', 'GET', '/api/1/energy_sites/{energy_site_id}/telemetry_history', 'energy_device_data', 'user', 0, 1, NULL, NULL),
  ('energy_command.energy_sites.site.time_of_use_settings.post', 'energy_command', 'POST', '/api/1/energy_sites/{energy_site_id}/time_of_use_settings', 'energy_cmds', 'user', 0, 0, NULL, NULL),
  ('vehicle.invitations.redeem.post', 'vehicle', 'POST', '/api/1/invitations/redeem', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('energy_product.products.get', 'energy_product', 'GET', '/api/1/products', 'energy_device_data', 'user', 0, 1, 'Energy products mapped to the account (Powerwall, solar, wall connector).', NULL),
  ('vehicle.vehicles.get', 'vehicle', 'GET', '/api/1/vehicles', 'vehicle_device_data', 'user', 0, 1, 'List vehicles belonging to the account (paginated, default 100).', NULL),
  ('fleet_telemetry.vehicles.fleet_status.post', 'fleet_telemetry', 'POST', '/api/1/vehicles/fleet_status', 'vehicle_device_data', 'user', 0, 1, 'Vehicle state relative to this application (key, firmware, telemetry version).', NULL),
  ('fleet_telemetry_config.vehicles.fleet_telemetry_config.post', 'fleet_telemetry_config', 'POST', '/api/1/vehicles/fleet_telemetry_config', 'vehicle_device_data', 'user', 0, 1, 'Create or update a fleet telemetry config, signed by the virtual key.', NULL),
  ('fleet_telemetry_config.vehicles.fleet_telemetry_config_jws.post', 'fleet_telemetry_config', 'POST', '/api/1/vehicles/fleet_telemetry_config_jws', 'vehicle_device_data', 'user', 0, 1, 'Configure telemetry with a pre-signed JWS token. Not recommended.', NULL),
  ('vehicle.vehicles.id.invitations.id.revoke.post', 'vehicle', 'POST', '/api/1/vehicles/{id}/invitations/{id}/revoke', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}', 'vehicle_device_data', 'user', 0, 1, 'Return summary information about one vehicle.', NULL),
  ('vehicle_command.vehicles.vin.command.actuate_trunk.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/actuate_trunk', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.add_charge_schedule.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/add_charge_schedule', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.add_precondition_schedule.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/add_precondition_schedule', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.adjust_volume.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/adjust_volume', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.auto_conditioning_start.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/auto_conditioning_start', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.auto_conditioning_stop.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/auto_conditioning_stop', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.cancel_software_update.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/cancel_software_update', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_max_range.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_max_range', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_port_door_close.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_port_door_close', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_port_door_open.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_port_door_open', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_standard.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_standard', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_start.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_start', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.charge_stop.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/charge_stop', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.clear_pin_to_drive_admin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/clear_pin_to_drive_admin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.door_lock.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/door_lock', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.door_unlock.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/door_unlock', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.erase_user_data.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/erase_user_data', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.flash_lights.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/flash_lights', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.guest_mode.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/guest_mode', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.honk_horn.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/honk_horn', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_next_fav.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_next_fav', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_next_track.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_next_track', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_prev_fav.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_prev_fav', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_prev_track.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_prev_track', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_toggle_playback.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_toggle_playback', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_volume_down.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_volume_down', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.media_volume_up.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/media_volume_up', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.navigation_gps_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/navigation_gps_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.navigation_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/navigation_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.navigation_sc_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/navigation_sc_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.navigation_waypoints_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/navigation_waypoints_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.parental_controls_activate.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/parental_controls_activate', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.parental_controls_clear_pin_admin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/parental_controls_clear_pin_admin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.parental_controls_deactivate.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/parental_controls_deactivate', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.parental_controls_enable_setting.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/parental_controls_enable_setting', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.parental_controls_set_speed_limit.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/parental_controls_set_speed_limit', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_auto_seat_climate_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_auto_seat_climate_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_auto_steering_wheel_heat_climate_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_auto_steering_wheel_heat_climate_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_boombox.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_boombox', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_seat_cooler_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_seat_cooler_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_seat_heater_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_seat_heater_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_start_drive.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_start_drive', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_steering_wheel_heat_level_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_steering_wheel_heat_level_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remote_steering_wheel_heater_request.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remote_steering_wheel_heater_request', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remove_charge_schedule.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remove_charge_schedule', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.remove_precondition_schedule.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/remove_precondition_schedule', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.reset_pin_to_drive_pin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/reset_pin_to_drive_pin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.reset_valet_pin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/reset_valet_pin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.schedule_software_update.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/schedule_software_update', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_bioweapon_mode.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_bioweapon_mode', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_cabin_overheat_protection.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_cabin_overheat_protection', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_charge_limit.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_charge_limit', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_charging_amps.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_charging_amps', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_climate_keeper_mode.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_climate_keeper_mode', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_cop_temp.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_cop_temp', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_pin_to_drive.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_pin_to_drive', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_preconditioning_max.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_preconditioning_max', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_scheduled_charging.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_scheduled_charging', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_scheduled_departure.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_scheduled_departure', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_sentry_mode.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_sentry_mode', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_temps.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_temps', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_valet_mode.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_valet_mode', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.set_vehicle_name.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/set_vehicle_name', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.speed_limit_activate.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/speed_limit_activate', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.speed_limit_clear_pin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/speed_limit_clear_pin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.speed_limit_clear_pin_admin.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/speed_limit_clear_pin_admin', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.speed_limit_deactivate.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/speed_limit_deactivate', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.speed_limit_set_limit.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/speed_limit_set_limit', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.sun_roof_control.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/sun_roof_control', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.trigger_homelink.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/trigger_homelink', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.upcoming_calendar_entries.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/upcoming_calendar_entries', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle_command.vehicles.vin.command.window_control.post', 'vehicle_command', 'POST', '/api/1/vehicles/{vin}/command/window_control', 'vehicle_cmds', 'user', 1, 0, NULL, NULL),
  ('vehicle.vehicles.vin.drivers.delete', 'vehicle', 'DELETE', '/api/1/vehicles/{vin}/drivers', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.drivers.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/drivers', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('fleet_telemetry_config.vehicles.vin.fleet_telemetry_config.delete', 'fleet_telemetry_config', 'DELETE', '/api/1/vehicles/{vin}/fleet_telemetry_config', 'vehicle_device_data', 'user', 0, 1, 'Get or delete a vehicle''s fleet telemetry config.', NULL),
  ('fleet_telemetry_config.vehicles.vin.fleet_telemetry_config.get', 'fleet_telemetry_config', 'GET', '/api/1/vehicles/{vin}/fleet_telemetry_config', 'vehicle_device_data', 'user', 0, 1, 'Get or delete a vehicle''s fleet telemetry config.', NULL),
  ('fleet_telemetry.vehicles.vin.fleet_telemetry_errors.get', 'fleet_telemetry', 'GET', '/api/1/vehicles/{vin}/fleet_telemetry_errors', 'vehicle_device_data', 'user', 0, 1, 'Recent telemetry errors reported by the vehicle.', NULL),
  ('vehicle.vehicles.vin.invitations.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/invitations', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.invitations.post', 'vehicle', 'POST', '/api/1/vehicles/{vin}/invitations', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.mobile_enabled.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/mobile_enabled', 'vehicle_device_data', 'user', 0, 1, 'Whether mobile access is enabled for the vehicle.', NULL),
  ('vehicle.vehicles.vin.nearby_charging_sites.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/nearby_charging_sites', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.recent_alerts.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/recent_alerts', 'vehicle_device_data', 'user', 0, 1, 'Recent vehicle alerts; resolves against tesla_alert_catalog.', NULL),
  ('vehicle.vehicles.vin.release_notes.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/release_notes', 'vehicle_device_data', 'user', 0, 1, 'Firmware release notes.', NULL),
  ('vehicle.vehicles.vin.service_data.get', 'vehicle', 'GET', '/api/1/vehicles/{vin}/service_data', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle.vehicles.vin.signed_command.post', 'vehicle', 'POST', '/api/1/vehicles/{vin}/signed_command', 'vehicle_device_data', 'user', 0, 1, NULL, NULL),
  ('vehicle_data.vehicles.vin.vehicle_data.get', 'vehicle_data', 'GET', '/api/1/vehicles/{vin}/vehicle_data', 'vehicle_device_data', 'user', 0, 1, 'Live read from the vehicle. Expensive; telemetry is preferred.', NULL),
  ('vehicle.vehicles.vin.wake_up.post', 'vehicle', 'POST', '/api/1/vehicles/{vin}/wake_up', 'vehicle_device_data', 'user', 0, 1, 'Wake the vehicle from sleep. Billed per wake; avoided by design.', NULL),
  ('enterprise.fleet_telemetry_config.create.post', 'enterprise', 'POST', '/api/1/enterprise/fleet_telemetry_config', 'enterprise_management', 'partner', 0, 0, 'Enterprise-wide telemetry configuration. Not enabled at MVP (F03-R06).', NULL),
  ('enterprise.vehicles.list.get', 'enterprise', 'GET', '/api/1/enterprise/vehicles', 'enterprise_management', 'partner', 0, 0, 'Enterprise vehicle inventory. Not enabled at MVP (F03-R06).', NULL);

INSERT OR REPLACE INTO tesla_catalog_load (catalog_name, source_name,
  source_sha256, source_rows, loaded_rows, loaded_at, loader_version) VALUES
  ('endpoint', 'developer.tesla.com endpoints docs', '300372c2718cc32edbdc3b682bfdbde646d408354272da48cf1794bd5202973a', 107, 107, '2026-10-02T00:00:00Z', 'build-endpoints.py/1.0.0');
