/**
 * FEATURE-12: Vehicle Telemetry Configurator — Group Management
 *
 * Group scope is a first-class, owner-curated entity (R-17 resolution),
 * NOT a binding to F06's derived segment keys. The derived key is an OUTPUT,
 * recomputed per export; a scope bound to it would silently stop applying
 * when the derivation changed.
 */

export interface VehicleGroup {
  group_id: string
  name: string
  description?: string
  created_at: string
  updated_at: string
}

export interface GroupMember {
  group_id: string
  vin: string
  added_at: string
}

/**
 * Create a new vehicle group.
 * The group_id is generated by the caller (ULID) or generated here.
 */
export async function createVehicleGroup(
  db: D1Database,
  params: {
    group_id: string
    name: string
    description?: string
    nowIso?: string
  }
): Promise<VehicleGroup> {
  const nowIso = params.nowIso ?? new Date().toISOString()

  await db
    .prepare(
      `INSERT INTO tesla_vehicle_group (group_id, name, description, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?)`
    )
    .bind(params.group_id, params.name, params.description ?? null, nowIso, nowIso)
    .run()

  return {
    group_id: params.group_id,
    name: params.name,
    description: params.description,
    created_at: nowIso,
    updated_at: nowIso,
  }
}

/**
 * Get a vehicle group by ID.
 */
export async function getVehicleGroup(
  db: D1Database,
  group_id: string
): Promise<VehicleGroup | null> {
  const row = await db
    .prepare('SELECT group_id, name, description, created_at, updated_at FROM tesla_vehicle_group WHERE group_id = ?')
    .bind(group_id)
    .first<VehicleGroup>()
  return row ?? null
}

/**
 * List all vehicle groups.
 */
export async function listVehicleGroups(
  db: D1Database
): Promise<VehicleGroup[]> {
  const res = await db
    .prepare('SELECT group_id, name, description, created_at, updated_at FROM tesla_vehicle_group ORDER BY created_at DESC')
    .all<VehicleGroup>()
  return res.results ?? []
}

/**
 * Update a vehicle group.
 */
export async function updateVehicleGroup(
  db: D1Database,
  params: {
    group_id: string
    name?: string
    description?: string
    nowIso?: string
  }
): Promise<number> {
  const nowIso = params.nowIso ?? new Date().toISOString()
  const updates: string[] = []
  const binds: unknown[] = []

  if (params.name !== undefined) {
    updates.push('name = ?')
    binds.push(params.name)
  }
  if (params.description !== undefined) {
    updates.push('description = ?')
    binds.push(params.description)
  }
  if (updates.length === 0) return 0

  updates.push('updated_at = ?')
  binds.push(nowIso)
  binds.push(params.group_id)

  const result = await db
    .prepare(`UPDATE tesla_vehicle_group SET ${updates.join(', ')} WHERE group_id = ?`)
    .bind(...binds)
    .run()
  return result.meta.changes ?? 0
}

/**
 * Delete a vehicle group (cascades to members and scope entries).
 */
export async function deleteVehicleGroup(
  db: D1Database,
  group_id: string
): Promise<number> {
  const result = await db
    .prepare('DELETE FROM tesla_vehicle_group WHERE group_id = ?')
    .bind(group_id)
    .run()
  return result.meta.changes ?? 0
}

/**
 * Add a vehicle to a group.
 */
export async function addVehicleToGroup(
  db: D1Database,
  params: {
    group_id: string
    vin: string
    nowIso?: string
  }
): Promise<GroupMember> {
  const nowIso = params.nowIso ?? new Date().toISOString()

  await db
    .prepare(
      `INSERT INTO tesla_vehicle_group_member (group_id, vin, added_at)
       VALUES (?, ?, ?)
       ON CONFLICT (group_id, vin) DO UPDATE SET added_at = excluded.added_at`
    )
    .bind(params.group_id, params.vin, nowIso)
    .run()

  return {
    group_id: params.group_id,
    vin: params.vin,
    added_at: nowIso,
  }
}

/**
 * Remove a vehicle from a group.
 */
export async function removeVehicleFromGroup(
  db: D1Database,
  group_id: string,
  vin: string
): Promise<number> {
  const result = await db
    .prepare('DELETE FROM tesla_vehicle_group_member WHERE group_id = ? AND vin = ?')
    .bind(group_id, vin)
    .run()
  return result.meta.changes ?? 0
}

/**
 * List members of a group.
 */
export async function listGroupMembers(
  db: D1Database,
  group_id: string
): Promise<GroupMember[]> {
  const res = await db
    .prepare('SELECT group_id, vin, added_at FROM tesla_vehicle_group_member WHERE group_id = ? ORDER BY added_at DESC')
    .bind(group_id)
    .all<GroupMember>()
  return res.results ?? []
}

/**
 * Get all groups a VIN belongs to.
 */
export async function getGroupsForVehicle(
  db: D1Database,
  vin: string
): Promise<VehicleGroup[]> {
  const res = await db
    .prepare(
      `SELECT g.group_id, g.name, g.description, g.created_at, g.updated_at
       FROM tesla_vehicle_group g
       JOIN tesla_vehicle_group_member m ON m.group_id = g.group_id
       WHERE m.vin = ?`
    )
    .bind(vin)
    .all<VehicleGroup>()
  return res.results ?? []
}