/**
 * Token encryption at rest (FRS-010 F02-R05).
 *
 * A Tesla refresh token is a bearer credential for a member's vehicle. It must
 * not sit in the database in the clear: a database export, a support dump, or an
 * operator with read access would otherwise hand over live vehicle access for
 * every member.
 *
 * AES-GCM with a 256-bit key held as a Worker secret. GCM is chosen over CBC
 * because it authenticates as well as encrypts — a tampered ciphertext fails to
 * decrypt rather than yielding attacker-influenced plaintext.
 *
 * The `key_version` on each row lets the key be rotated without a flag day: rows
 * written under v1 stay readable while new writes use v2. Rotation is a
 * deliberate operation, and Tesla refresh tokens are the one thing here that
 * cannot simply be regenerated by asking the member again without friction.
 */

/** Raised when the token encryption key is absent from the deployment. */
export class TokenKeyMissingError extends Error {
  constructor() {
    super('TOKEN_ENCRYPTION_KEY is not configured')
    this.name = 'TokenKeyMissingError'
  }
}

export interface SealedToken {
  ciphertext: string
  iv: string
  keyVersion: number
}

const encoder = new TextEncoder()
const decoder = new TextDecoder()

function toBase64(bytes: Uint8Array): string {
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

function fromBase64(value: string): Uint8Array {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

/**
 * Derive the AES key from the configured secret.
 *
 * The secret is imported as raw key material, which requires it to be exactly 32
 * bytes. A short or malformed secret fails here with a clear message rather than
 * producing a key that silently differs between deployments — which would make
 * stored tokens undecryptable with no indication why.
 */
async function importKey(secret: string): Promise<CryptoKey> {
  if (!secret) throw new TokenKeyMissingError()
  const raw = fromBase64(secret)
  if (raw.length !== 32) {
    throw new Error(
      `TOKEN_ENCRYPTION_KEY must be 32 bytes base64-encoded (got ${raw.length} bytes); ` +
      'generate one with: openssl rand -base64 32',
    )
  }
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt'])
}

/** Encrypt a token. A fresh random IV is generated for every call. */
export async function sealToken(
  plaintext: string,
  secret: string,
  keyVersion = 1,
): Promise<SealedToken> {
  const key = await importKey(secret)
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    encoder.encode(plaintext),
  )
  return {
    ciphertext: toBase64(new Uint8Array(ciphertext)),
    iv: toBase64(iv),
    keyVersion,
  }
}

/**
 * Decrypt a token. Throws if the ciphertext was tampered with or the key is
 * wrong; callers treat a failure as "the member must reconnect", never as a
 * reason to fall back to storing plaintext.
 */
export async function openToken(sealed: SealedToken, secret: string): Promise<string> {
  const key = await importKey(secret)
  const plaintext = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: fromBase64(sealed.iv) },
    key,
    fromBase64(sealed.ciphertext),
  )
  return decoder.decode(plaintext)
}

/**
 * Generate a fresh 32-byte key, for provisioning.
 * Run: `node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"`
 */
export function generateTokenKey(): string {
  return toBase64(crypto.getRandomValues(new Uint8Array(32)))
}
